name: Change/Feature Request  
description: Request a Change and/or a New Feature
title: "Subject"
labels: [Change_Request, Feature_Request]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: RAM and/or Specifications
    - label: Certification
    - label: Testbed
    - label: Open Source Strategy Components
    - label: IDS Rulebook
    - label: Knowledge Base
    - label: Use Case Radar
      required: true
- type: textarea
  attributes:
    label: As a(n)
    description: Please describe your request in more detail
  validations:
    required: false
- type: textarea
  attributes:
    label: I want to
    description: Please describe your request in more detail
  validations:
    required: false
- type: textarea
  attributes:
    label: So that
    description: Please describe your request in more detail
  validations:
    required: false
- type: textarea
  attributes:
    label: Environment
    description: |
      examples:
        - **OS**: Ubuntu 20.04
        - **Node**: 13.14.0
        - **npm**: 7.6.3
    value: |
        - OS:
        - Node:
        - npm:
    render: markdown
  validations:
    required: false
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
