name: Change/Feature Request  
description: Via filling in this form, you may request a change and/or a new feature for an IDS asset. Your opinion will be added as an issue under this repo.
title: "Subject"
labels: [Change_Request, Feature_Request]
body:
- type: checkboxes
  attributes:
    label: To which IDS artifact(s) your request is related to? 
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: RAM and/or Specifications
    - label: Certification
    - label: Testbed
    - label: Open Source Strategy Components
    - label: IDS Rulebook
    - label: Knowledge Base
    - label: Use Case Radar
    - label: Other(s)
- type: textarea
  attributes:
    label: As a(n)
    description: Please describe your request in more detail
  validations:
    required: false
- type: textarea
  attributes:
    label: I want to
    description: Please describe your request in more detail
  validations:
    required: false
- type: textarea
  attributes:
    label: So that
    description: Please describe your request in more detail
  validations:
    required: false
- type: textarea
  attributes:
    label: So that
    description: Please describe your request in more detail
  validations:
    required: false
